//
// Created by rafae on 14/12/2025.
//

#include "API/GamepadDefs.h"

#include <godot_cpp/core/class_db.hpp>

using namespace godot;

void GamepadDefs::_bind_methods() {

    // LedMic
    BIND_ENUM_CONSTANT(MIC_ON);
    BIND_ENUM_CONSTANT(MIC_OFF);
    BIND_ENUM_CONSTANT(MIC_PULSE);

    // LedPlayer
    BIND_ENUM_CONSTANT(PLAYER_OFF);
    BIND_ENUM_CONSTANT(PLAYER_ONE);
    BIND_ENUM_CONSTANT(PLAYER_TWO);
    BIND_ENUM_CONSTANT(PLAYER_THREE);
    BIND_ENUM_CONSTANT(PLAYER_ALL);

    // LedBrightness
    BIND_ENUM_CONSTANT(BRIGHTNESS_LOW);
    BIND_ENUM_CONSTANT(BRIGHTNESS_MEDIUM);
    BIND_ENUM_CONSTANT(BRIGHTNESS_HIGH);

    // AudioFeature
    BIND_ENUM_CONSTANT(AUDIO_ON);
    BIND_ENUM_CONSTANT(AUDIO_OFF);

    // DeviceFeature
    BIND_ENUM_CONSTANT(FEATURE_OFF);
    BIND_ENUM_CONSTANT(DEFAULT_RUMBLE);
    BIND_ENUM_CONSTANT(HAPTICS_RUMBLE);

    // TriggerSoftness
    BIND_ENUM_CONSTANT(SOFTNESS_OFF);
    BIND_ENUM_CONSTANT(VERY_RIGID);
    BIND_ENUM_CONSTANT(RIGID);
    BIND_ENUM_CONSTANT(MEDIUM_SOFTNESS);
    BIND_ENUM_CONSTANT(SOFT);
    BIND_ENUM_CONSTANT(VERY_SOFT);

    // TriggerFeedbackIntensity
    BIND_ENUM_CONSTANT(FEEDBACK_DISABLED);
    BIND_ENUM_CONSTANT(FEEDBACK_LOW);
    BIND_ENUM_CONSTANT(FEEDBACK_MEDIUM);
    BIND_ENUM_CONSTANT(FEEDBACK_HIGH);

    // TriggerForceIntensity
    BIND_ENUM_CONSTANT(FORCE_DISABLED);
    BIND_ENUM_CONSTANT(FORCE_LOW);
    BIND_ENUM_CONSTANT(FORCE_MEDIUM);
    BIND_ENUM_CONSTANT(FORCE_HIGH);

    // TriggerPosition
    BIND_ENUM_CONSTANT(POS_OFF);
    BIND_ENUM_CONSTANT(POS_START);
    BIND_ENUM_CONSTANT(POS_MIDDLE);
    BIND_ENUM_CONSTANT(POS_BEFORE_END);
    BIND_ENUM_CONSTANT(POS_END);

    // TriggerPositionMask
    BIND_ENUM_CONSTANT(MASK_POS_OFF);
    BIND_ENUM_CONSTANT(MASK_POS_START);
    BIND_ENUM_CONSTANT(MASK_POS_EARLY);
    BIND_ENUM_CONSTANT(MASK_POS_MIDDLE);
    BIND_ENUM_CONSTANT(MASK_POS_LATE);
    BIND_ENUM_CONSTANT(MASK_POS_END);

    // TriggerForceMask
    BIND_ENUM_CONSTANT(MASK_FORCE_OFF);
    BIND_ENUM_CONSTANT(MASK_FORCE_VERY_LOW);
    BIND_ENUM_CONSTANT(MASK_FORCE_LOW);
    BIND_ENUM_CONSTANT(MASK_FORCE_MEDIUM_LOW);
    BIND_ENUM_CONSTANT(MASK_FORCE_MEDIUM);
    BIND_ENUM_CONSTANT(MASK_FORCE_MEDIUM_HIGH);
    BIND_ENUM_CONSTANT(MASK_FORCE_HIGH);
    BIND_ENUM_CONSTANT(MASK_FORCE_VERY_HIGH);
    BIND_ENUM_CONSTANT(MASK_FORCE_MAX);

    // TriggerAmplitude
    BIND_ENUM_CONSTANT(AMP_NONE);
    BIND_ENUM_CONSTANT(AMP_LOW);
    BIND_ENUM_CONSTANT(AMP_MEDIUM);
    BIND_ENUM_CONSTANT(AMP_HIGH);

    // SnapBack
    BIND_ENUM_CONSTANT(SNAP_NONE);
    BIND_ENUM_CONSTANT(SNAP_LOW);
    BIND_ENUM_CONSTANT(SNAP_MEDIUM);
    BIND_ENUM_CONSTANT(SNAP_HIGH);

    // WeaponTrigger
    BIND_ENUM_CONSTANT(WEAPON_NONE);
    BIND_ENUM_CONSTANT(WEAPON_LOW);
    BIND_ENUM_CONSTANT(WEAPON_MEDIUM);
    BIND_ENUM_CONSTANT(WEAPON_HIGH);
    BIND_ENUM_CONSTANT(WEAPON_MAX);

    // TriggerEffectBehavior
    BIND_ENUM_CONSTANT(LOCALIZED);
    BIND_ENUM_CONSTANT(SUSTAINED);

    // AutoGunStrength
    BIND_ENUM_CONSTANT(GUN_LIGHT);
    BIND_ENUM_CONSTANT(GUN_MEDIUM);
    BIND_ENUM_CONSTANT(GUN_HEAVY);

    // GamepadHand
    BIND_ENUM_CONSTANT(LEFT_HAND);
    BIND_ENUM_CONSTANT(RIGHT_HAND);
    BIND_ENUM_CONSTANT(ANY_HAND);
}